#!/usr/bin/env bash
# Installs Nginx with the following configurations:
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service restart nginx
