#!/usr/bin/env bash
# Installs Nginx with the following configurations:
apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx start
