#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location /redirect_me {
                return 301 https://github.com/the1Riddle
        }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
