#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

echo '
backend web-backend
        balance roundrobin
        option forwardfor
        server 338390-web-01 52.204.118.62:80 check
        server 338390-web-02 100.27.10.76:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
