#!/usr/bin/env bash
#  Bash script that transfers a file from our client to a server:
if [ "$#" -lt 3 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]
then
        scp -o StrictHostKeyChecking=no "$1" "ubuntu@$2:~/"
else
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "ubuntu@$2:~/"
fi
