#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.

for x in {1..100}
do
	if ((x % 3 == 0 && x % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((x % 3 == 0))
	then
		echo "Fizz";
	elif ((x % 5 == 0))
	then
		echo "Buzz";
	else
		echo "$x";
	fi
done
