#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes
Hour=0
while [ $Hour -lt 13 ]
do
	echo "Hour: $Hour";
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min";
		((min++));
	done
	((Hour++));
done
